import OurProducts from '@/Components/Home/OurProduct'
import Exclusive from '@/Components/Home/exclusive'
import Header from '@/Components/Home/header'
import Icon from '@/Components/Home/icon'
import Navbar from '@/Components/Home/navbar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tassels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Header/>
      <Icon/>
      <Exclusive/>
      <OurProducts/>
    </>
  )
}
