import Faq from '@/Components/Home/Faq'
import OurProducts from '@/Components/Home/OurProduct'
import Review from '@/Components/Home/Review'
import Exclusive from '@/Components/Home/exclusive'
import FollowUs from '@/Components/Home/followUs'
import Franchises from '@/Components/Home/franchises'
import GetQuote from '@/Components/Home/getQuote'
import Header from '@/Components/Home/header'
import Icon from '@/Components/Home/icon'
import Navbar from '@/Components/Home/navbar'
import TasselsFooter from '@/Components/footer'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tassels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <Icon />
      <Exclusive />
      <OurProducts />
      <GetQuote />
      <Franchises />
      <FollowUs />
      <Review />
      <Faq />
      <TasselsFooter />
    </>
  )
}
